In [9]:
import pandas as pd
import os
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

In [10]:
ipl_data = pd.DataFrame(pd.read_csv(r"C:\Users\allex\Downloads\IPL2025Batters.csv"))

In [11]:
ipl_data.head()

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37

In [12]:
mi_batters = ipl_data[ipl_data['Team'] == 'MI']
mi_batters.head()

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
15,Rohit Sharma,MI,418,15,15,1,81,29.86,280,149.28,0,4,41,22
19,Ryan Rickelton,MI,388,14,14,1,62*,29.85,257,150.97,0,3,47,17
25,N Tilak Varma,MI,343,16,13,2,59,31.18,248,138.30,0,2,23,16
40,Naman Dhir,MI,252,16,12,4,46,31.50,138,182.60,0,0,24,13

In [13]:
# Establishing connection....

url = URL.create(
    drivername="mysql+mysqldb",
    username="root",
    password=os.getenv("MYSQL_PASSWORD"),
    host="127.0.0.1",
    port=3306,
    database="session_20"
)

engine = create_engine(url)

In [14]:
try:
    mi_batters.to_sql('mi_batters', con=engine, if_exists= 'append', index= False, method='multi')

except Exception as e:
    print(e)